title: Blog
description: シンプルなブログ
url: "https://6uclz1.github.io"
baseurl: "/claude-code-blog-site"
author: Blog Author
markdown: kramdown
permalink: /:year/:month/:day/:title
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/page:num/"

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# RSS Feed Configuration
feed:
  posts_limit: 20
  excerpt_only: false
  collections:
    - posts

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - .github/