title: Blog
description: シンプルなブログ
url: "https://username.github.io"
baseurl: "/claude-code-blog-site"
markdown: kramdown
permalink: /:year/:month/:day/:title
highlighter: rouge
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/