version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --force_polling

  python-scripts:
    image: python:3.11-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

volumes:
  bundle_cache: