name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker services
        run: docker compose build
      
      - name: Run tests with coverage
        run: |
          docker compose run --rm python-scripts sh -c "
            # 必要なシステムライブラリを先にインストール（Debian/Ubuntu 系）
            apt-get update && apt-get install -y \
              ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 \
              libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 \
              libgbm1 libxss1 wget \
            && rm -rf /var/lib/apt/lists/* \
            && pip install -r requirements.txt \
            # pip が playwright を見つけられないケース対策で pip を最新化（任意）
            && python -m pip install --upgrade pip setuptools wheel \
            && pip install playwright \
            # ブラウザと OS 依存パッケージもまとめてインストール
            && PLAYWRIGHT_BROWSERS_PATH=/ms-playwright python -m playwright install --with-deps \
            && python test_runner.py --coverage
          "
      
      - name: Check Jekyll build
        run: |
          docker compose run --rm jekyll sh -c "
            bundle install &&
            bundle exec jekyll doctor &&
            bundle exec jekyll build
          "