name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker services
        run: docker compose build
      
      - name: Run tests with coverage
        run: |
          docker compose run --rm python-scripts sh -c "
            pip install -r requirements.txt &&
            python test_runner.py --coverage
          "
      
      - name: Check Jekyll build
        run: |
          docker compose run --rm jekyll sh -c "
            bundle install &&
            bundle exec jekyll doctor &&
            bundle exec jekyll build
          "