name: Update Blog with Hatena Bookmarks

on:
  schedule:
    - cron: '0 23 * * *'  # 毎日8:00 JST (23:00 UTC)
  workflow_dispatch:      # 手動実行も可能

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-blog:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker services
        run: docker compose build
      
      - name: Run fetch and summarize script in Docker
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          docker compose run --rm python-scripts sh -c "
            pip install -r requirements.txt &&
            python scripts/fetch_and_summarize.py
          "
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git add _posts/
          git commit -m "自動更新: はてなブックマークから記事を要約して追加 $(date '+%Y-%m-%d %H:%M:%S')"
          git push
      
      - name: Build Jekyll site with Docker
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          docker build -f Dockerfile.production -t jekyll-site .
          docker run --rm -v $PWD/_site:/output jekyll-site sh -c "cp -r /usr/share/nginx/html/* /output/"
      
      - name: Setup Pages
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
      
      - name: Deploy to GitHub Pages
        if: steps.verify-changed-files.outputs.changed == 'true'
        id: deployment
        uses: actions/deploy-pages@v4